CREATE TABLE tent_entries (
    ent_entid SERIAL PRIMARY KEY,
    ent_title TEXT NOT NULL,
    ent_summary TEXT NOT NULL,
    ent_categories TEXT[] DEFAULT '{}',
    ent_source_url TEXT,
    ent_article_date TEXT,
    ent_country TEXT,
    ent_author TEXT,
    ent_publication TEXT
);

CREATE TABLE targ_arguments (
    arg_argid SERIAL PRIMARY KEY,
    arg_entid INTEGER NOT NULL,
    arg_text TEXT NOT NULL,
    arg_relevance INT DEFAULT 50
);

CREATE TABLE tsrc_sources (
    src_srcid SERIAL PRIMARY KEY,
    src_entid INTEGER NOT NULL,
    src_url TEXT NOT NULL,
    src_title TEXT
);

CREATE TABLE xlg_logging (
    lg_lgid         integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    lg_severity     character(1),
    lg_caller       character varying DEFAULT '',
    lg_functionname character varying NOT NULL,
    lg_msg          character varying NOT NULL,
    lg_datetime     timestamp with time zone NOT NULL,
    CONSTRAINT xlg_logging_pkey PRIMARY KEY (lg_lgid)
);
