-- Name: targ_arguments; Type: TABLE;
--

CREATE TABLE public.targ_arguments (
    arg_argid integer NOT NULL,
    arg_entid integer NOT NULL,
    arg_text text NOT NULL,
    arg_relevance integer DEFAULT 50
);

CREATE SEQUENCE public.targ_arguments_arg_argid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE ONLY public.targ_arguments ALTER COLUMN arg_argid SET DEFAULT nextval('public.targ_arguments_arg_argid_seq'::regclass);

ALTER TABLE ONLY public.targ_arguments
    ADD CONSTRAINT targ_arguments_pkey PRIMARY KEY (arg_argid);

--
-- Name: tent_entries; Type: TABLE;
--

CREATE TABLE public.tent_entries (
    ent_entid integer NOT NULL,
    ent_title text NOT NULL,
    ent_summary text NOT NULL,
    ent_categories text[] DEFAULT '{}'::text[],
    ent_source_url text,
    ent_article_date text,
    ent_country text,
    ent_author text,
    ent_publication text
);

CREATE SEQUENCE public.tent_entries_ent_entid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE ONLY public.tent_entries ALTER COLUMN ent_entid SET DEFAULT nextval('public.tent_entries_ent_entid_seq'::regclass);

ALTER TABLE ONLY public.tent_entries
    ADD CONSTRAINT tent_entries_pkey PRIMARY KEY (ent_entid);

--
-- Name: tsrc_sources; Type: TABLE;
--

CREATE TABLE public.tsrc_sources (
    src_srcid integer NOT NULL,
    src_entid integer NOT NULL,
    src_url text NOT NULL,
    src_title text
);

CREATE SEQUENCE public.tsrc_sources_src_srcid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE ONLY public.tsrc_sources ALTER COLUMN src_srcid SET DEFAULT nextval('public.tsrc_sources_src_srcid_seq'::regclass);

ALTER TABLE ONLY public.tsrc_sources
    ADD CONSTRAINT tsrc_sources_pkey PRIMARY KEY (src_srcid);

--
-- Name: xlg_logging; Type: TABLE;
--

CREATE TABLE public.xlg_logging (
    lg_lgid integer NOT NULL,
    lg_severity character(1),
    lg_caller character varying DEFAULT ''::character varying,
    lg_functionname character varying NOT NULL,
    lg_msg character varying NOT NULL,
    lg_datetime timestamp with time zone NOT NULL
);

ALTER TABLE public.xlg_logging ALTER COLUMN lg_lgid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.xlg_logging_lg_lgid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.xlg_logging
    ADD CONSTRAINT xlg_logging_pkey PRIMARY KEY (lg_lgid);
